# Generated by Django 3.1.1 on 2020-09-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200923_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkdin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
    ]
